import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { PnLStatement, BalanceSheet, TaxSummary, BusinessInfo, VarianceRow } from '../types';

const BRAND_COLOR: [number, number, number] = [31, 87, 164];
const ACCENT: [number, number, number] = [16, 185, 129];
const LIGHT_GRAY: [number, number, number] = [248, 250, 252];
const DARK: [number, number, number] = [15, 23, 42];

function fmt(n: number): string {
  const abs = Math.abs(n);
  const s = abs.toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 });
  return n < 0 ? `($${s})` : `$${s}`;
}

function header(doc: jsPDF, title: string, businessInfo: BusinessInfo, pageNum: number) {
  // Blue header bar
  doc.setFillColor(...BRAND_COLOR);
  doc.rect(0, 0, 210, 28, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('FinTrack Pro', 14, 11);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Financial Analysis & Tax Reporting', 14, 17);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 14, 25);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  const right = `${businessInfo.name} | Tax Year ${businessInfo.taxYear} | Page ${pageNum}`;
  doc.text(right, 210 - 14, 25, { align: 'right' });

  doc.setTextColor(...DARK);
}

function footer(doc: jsPDF) {
  const pageHeight = doc.internal.pageSize.height;
  doc.setFillColor(241, 245, 249);
  doc.rect(0, pageHeight - 12, 210, 12, 'F');
  doc.setFontSize(7);
  doc.setTextColor(100, 116, 139);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by FinTrack Pro | GAAP-Compliant Analysis | For Tax Reporting Purposes', 14, pageHeight - 4);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 210 - 14, pageHeight - 4, { align: 'right' });
  doc.setTextColor(...DARK);
}

export function exportPnLPDF(pnl: PnLStatement, businessInfo: BusinessInfo): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  header(doc, 'PROFIT & LOSS STATEMENT (Accrual Basis)', businessInfo, 1);

  const rows: [string, string][] = [
    ['REVENUE', ''],
    ['  Product Sales', fmt(pnl.revenue.productSales)],
    ['  Service Revenue', fmt(pnl.revenue.serviceRevenue)],
    ['  Other Income', fmt(pnl.revenue.otherIncome)],
    ['TOTAL REVENUE', fmt(pnl.revenue.total)],
    ['', ''],
    ['COST OF GOODS SOLD', ''],
    ['  Beginning Inventory', fmt(pnl.cogs.beginningInventory)],
    ['  Purchases', fmt(pnl.cogs.purchases)],
    ['  Less: Ending Inventory', fmt(-pnl.cogs.endingInventory)],
    ['  Direct Labor', fmt(pnl.cogs.directLabor)],
    ['TOTAL COGS', fmt(pnl.cogs.total)],
    ['', ''],
    ['GROSS PROFIT', `${fmt(pnl.grossProfit)}  (${pnl.grossMargin.toFixed(1)}%)`],
    ['', ''],
    ['OPERATING EXPENSES', ''],
    ['  Salaries & Wages', fmt(pnl.operatingExpenses.salaries)],
    ['  Rent/Lease', fmt(pnl.operatingExpenses.rent)],
    ['  Utilities', fmt(pnl.operatingExpenses.utilities)],
    ['  Insurance', fmt(pnl.operatingExpenses.insurance)],
    ['  Marketing & Advertising', fmt(pnl.operatingExpenses.marketing)],
    ['  Professional Services', fmt(pnl.operatingExpenses.professionalServices)],
    ['  Office & Supplies', fmt(pnl.operatingExpenses.officeSupplies)],
    ['  Equipment & Maintenance', fmt(pnl.operatingExpenses.equipmentMaintenance)],
    ['  Depreciation', fmt(pnl.operatingExpenses.depreciation)],
    ['  Bank Fees', fmt(pnl.operatingExpenses.bankFees)],
    ['  Other Operating', fmt(pnl.operatingExpenses.other)],
    ['TOTAL OPERATING EXPENSES', fmt(pnl.operatingExpenses.total)],
    ['', ''],
    ['OPERATING INCOME', `${fmt(pnl.operatingIncome)}  (${pnl.operatingMargin.toFixed(1)}%)`],
    ['', ''],
    ['OTHER INCOME / (EXPENSE)', ''],
    ['  Interest Income', fmt(pnl.otherItems.interestIncome)],
    ['  Interest Expense', fmt(-pnl.otherItems.interestExpense)],
    ['', ''],
    ['NET INCOME (BEFORE TAX)', fmt(pnl.netIncomeBeforeTax)],
    ['  Tax Provision (25%)', fmt(-pnl.taxProvision)],
    ['NET INCOME (AFTER TAX)', `${fmt(pnl.netIncomeAfterTax)}  (${pnl.netMargin.toFixed(1)}%)`],
  ];

  const totalRows = new Set(['TOTAL REVENUE', 'TOTAL COGS', 'GROSS PROFIT', 'TOTAL OPERATING EXPENSES', 'OPERATING INCOME', 'NET INCOME (BEFORE TAX)', 'NET INCOME (AFTER TAX)']);
  const sectionRows = new Set(['REVENUE', 'COST OF GOODS SOLD', 'OPERATING EXPENSES', 'OTHER INCOME / (EXPENSE)']);

  autoTable(doc, {
    startY: 34,
    body: rows.map(([label, value]) => [label, value]),
    columnStyles: { 0: { cellWidth: 130 }, 1: { cellWidth: 50, halign: 'right' } },
    styles: { fontSize: 9, cellPadding: { top: 1.5, bottom: 1.5, left: 4, right: 4 } },
    didParseCell: (data) => {
      const raw = data.row.raw as string[] | undefined;
      const label = String(raw?.[0] ?? '');
      if (totalRows.has(label)) {
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.fillColor = [219, 234, 254];
        data.cell.styles.lineWidth = { top: 0.3, bottom: 0.3, left: 0, right: 0 };
        data.cell.styles.lineColor = BRAND_COLOR;
      } else if (sectionRows.has(label)) {
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.fillColor = LIGHT_GRAY;
        data.cell.styles.textColor = BRAND_COLOR;
      }
    },
    theme: 'plain',
  });

  footer(doc);
  doc.save(`${businessInfo.name}_PnL_${businessInfo.taxYear}.pdf`);
}

export function exportBalanceSheetPDF(bs: BalanceSheet, businessInfo: BusinessInfo): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  header(doc, `BALANCE SHEET — As of December 31, ${businessInfo.taxYear}`, businessInfo, 1);

  const rows: [string, string][] = [
    ['ASSETS', ''],
    ['Current Assets', ''],
    ['  Cash & Cash Equivalents', fmt(bs.assets.current.cash)],
    ['  Accounts Receivable', fmt(bs.assets.current.accountsReceivable)],
    ['  Inventory', fmt(bs.assets.current.inventory)],
    ['  Prepaid Expenses', fmt(bs.assets.current.prepaidExpenses)],
    ['TOTAL CURRENT ASSETS', fmt(bs.assets.current.total)],
    ['', ''],
    ['Fixed Assets', ''],
    ['  Property, Plant & Equipment', fmt(bs.assets.fixed.propertyPlantEquipment)],
    ['  Less: Accumulated Depreciation', fmt(-bs.assets.fixed.accumulatedDepreciation)],
    ['NET FIXED ASSETS', fmt(bs.assets.fixed.net)],
    ['', ''],
    ['Other Assets', ''],
    ['  Security Deposits', fmt(bs.assets.other.securityDeposits)],
    ['TOTAL ASSETS', fmt(bs.assets.total)],
    ['', ''],
    ['LIABILITIES', ''],
    ['Current Liabilities', ''],
    ['  Accounts Payable', fmt(bs.liabilities.current.accountsPayable)],
    ['  Credit Card Payable', fmt(bs.liabilities.current.creditCardPayable)],
    ['  Sales Tax Payable', fmt(bs.liabilities.current.salesTaxPayable)],
    ['  Current Portion of Debt', fmt(bs.liabilities.current.currentDebt)],
    ['  Accrued Expenses', fmt(bs.liabilities.current.accruedExpenses)],
    ['TOTAL CURRENT LIABILITIES', fmt(bs.liabilities.current.total)],
    ['', ''],
    ['Long-Term Liabilities', ''],
    ['  Long-Term Debt', fmt(bs.liabilities.longTerm.longTermDebt)],
    ['TOTAL LIABILITIES', fmt(bs.liabilities.total)],
    ['', ''],
    ['EQUITY', ''],
    ['  Owner/Member Capital', fmt(bs.equity.ownerCapital)],
    ['  Retained Earnings (Prior Years)', fmt(bs.equity.retainedEarnings)],
    ['  Current Year Net Income', fmt(bs.equity.currentYearIncome)],
    ['TOTAL EQUITY', fmt(bs.equity.total)],
    ['', ''],
    ['TOTAL LIABILITIES + EQUITY', fmt(bs.totalLiabilitiesAndEquity)],
  ];

  const totalRows = new Set(['TOTAL CURRENT ASSETS', 'NET FIXED ASSETS', 'TOTAL ASSETS', 'TOTAL CURRENT LIABILITIES', 'TOTAL LIABILITIES', 'TOTAL EQUITY', 'TOTAL LIABILITIES + EQUITY']);
  const sectionRows = new Set(['ASSETS', 'LIABILITIES', 'EQUITY', 'Current Assets', 'Fixed Assets', 'Other Assets', 'Current Liabilities', 'Long-Term Liabilities']);

  autoTable(doc, {
    startY: 34,
    body: rows.map(r => [r[0], r[1]]),
    columnStyles: { 0: { cellWidth: 130 }, 1: { cellWidth: 50, halign: 'right' } },
    styles: { fontSize: 9, cellPadding: { top: 1.5, bottom: 1.5, left: 4, right: 4 } },
    didParseCell: (data) => {
      const raw = data.row.raw as string[] | undefined;
      const label = String(raw?.[0] ?? '');
      if (totalRows.has(label)) {
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.fillColor = label === 'TOTAL LIABILITIES + EQUITY' ? [219, 234, 254] : [241, 245, 249];
        data.cell.styles.lineWidth = { top: 0.3, bottom: 0.3, left: 0, right: 0 };
        data.cell.styles.lineColor = BRAND_COLOR;
      } else if (sectionRows.has(label)) {
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.fillColor = label === 'ASSETS' || label === 'LIABILITIES' || label === 'EQUITY' ? LIGHT_GRAY : [255, 255, 255];
        data.cell.styles.textColor = label === 'ASSETS' || label === 'LIABILITIES' || label === 'EQUITY' ? BRAND_COLOR : DARK;
      }
    },
    theme: 'plain',
  });

  footer(doc);
  doc.save(`${businessInfo.name}_BalanceSheet_${businessInfo.taxYear}.pdf`);
}

export function exportTaxSummaryPDF(
  tax: TaxSummary,
  pnl: PnLStatement,
  bs: BalanceSheet,
  businessInfo: BusinessInfo,
  varianceRows: VarianceRow[]
): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  // Cover page
  doc.setFillColor(...BRAND_COLOR);
  doc.rect(0, 0, 210, 60, 'F');
  doc.setFillColor(...ACCENT);
  doc.rect(0, 58, 210, 4, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('TAX REPORTING SUMMARY', 105, 28, { align: 'center' });
  doc.setFontSize(13);
  doc.setFont('helvetica', 'normal');
  doc.text(businessInfo.name.toUpperCase(), 105, 40, { align: 'center' });
  doc.setFontSize(11);
  doc.text(`Tax Year ${businessInfo.taxYear}  •  ${businessInfo.structure}  •  Accrual Basis`, 105, 50, { align: 'center' });

  doc.setTextColor(...DARK);
  doc.setFontSize(10);

  // Key metrics boxes
  const metrics = [
    { label: 'Total Revenue', value: fmt(pnl.revenue.total) },
    { label: 'Net Income', value: fmt(pnl.netIncomeAfterTax) },
    { label: 'Taxable Income', value: fmt(tax.taxableIncome) },
    { label: 'Est. Tax Liability', value: fmt(tax.estimatedAnnualTax) },
  ];

  metrics.forEach((m, i) => {
    const x = 14 + i * 47;
    doc.setFillColor(...LIGHT_GRAY);
    doc.roundedRect(x, 68, 44, 22, 2, 2, 'F');
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(m.label.toUpperCase(), x + 22, 75, { align: 'center' });
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...BRAND_COLOR);
    doc.text(m.value, x + 22, 84, { align: 'center' });
  });

  doc.setTextColor(...DARK);

  // Deduction table
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('DEDUCTION SUMMARY', 14, 100);

  autoTable(doc, {
    startY: 103,
    head: [['Deduction Category', 'Amount', 'Deductible']],
    body: [
      ['Cost of Goods Sold', fmt(tax.deductionBreakdown.cogs), '✓'],
      ['Salaries & Wages', fmt(tax.deductionBreakdown.salaries), '✓'],
      ['Rent/Lease Payments', fmt(tax.deductionBreakdown.rent), '✓'],
      ['Utilities & Occupancy', fmt(tax.deductionBreakdown.utilities), '✓'],
      ['Insurance Premiums', fmt(tax.deductionBreakdown.insurance), '✓'],
      ['Professional Services', fmt(tax.deductionBreakdown.professionalServices), '✓'],
      ['Depreciation', fmt(tax.deductionBreakdown.depreciation), '✓'],
      ['Interest Expense', fmt(tax.deductionBreakdown.interestExpense), '✓'],
      ['Other Expenses', fmt(tax.deductionBreakdown.other), '✓'],
      ['TOTAL DEDUCTIONS', fmt(tax.totalDeductions), ''],
    ],
    columnStyles: { 0: { cellWidth: 90 }, 1: { cellWidth: 55, halign: 'right' }, 2: { cellWidth: 30, halign: 'center' } },
    styles: { fontSize: 9 },
    headStyles: { fillColor: BRAND_COLOR, textColor: 255, fontStyle: 'bold' },
    didParseCell: (data) => {
      if (data.row.index === 9) {
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.fillColor = [219, 234, 254];
      }
    },
  });

  const y1 = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;

  // Variance analysis
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('CASH vs. ACCRUAL VARIANCE ANALYSIS', 14, y1);

  autoTable(doc, {
    startY: y1 + 3,
    head: [['Line Item', 'Cash Basis', 'Accrual Basis', 'Variance', 'Root Cause']],
    body: varianceRows.map(r => [r.lineItem, fmt(r.cashBasis), fmt(r.accrualBasis), fmt(r.variance), r.rootCause]),
    columnStyles: { 0: { cellWidth: 32 }, 1: { cellWidth: 25, halign: 'right' }, 2: { cellWidth: 25, halign: 'right' }, 3: { cellWidth: 22, halign: 'right' }, 4: { cellWidth: 76 } },
    styles: { fontSize: 7.5, cellPadding: 2 },
    headStyles: { fillColor: BRAND_COLOR, textColor: 255, fontStyle: 'bold', fontSize: 8 },
  });

  // Working capital
  const y2 = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('WORKING CAPITAL & LIQUIDITY', 14, y2);

  const ratioColor = (good: boolean): [number, number, number] => good ? ACCENT : [239, 68, 68];

  autoTable(doc, {
    startY: y2 + 3,
    body: [
      ['Current Ratio', bs.currentRatio.toFixed(2), bs.currentRatio >= 1.5 ? '✓ Healthy' : '⚠ Low', 'Benchmark: > 1.5'],
      ['Quick Ratio', bs.quickRatio.toFixed(2), bs.quickRatio >= 1.0 ? '✓ Healthy' : '⚠ Low', 'Benchmark: > 1.0'],
      ['Debt-to-Equity', bs.debtToEquity.toFixed(2), bs.debtToEquity <= 2.0 ? '✓ Healthy' : '⚠ High', 'Benchmark: < 2.0'],
      ['Working Capital', fmt(bs.workingCapital), bs.workingCapital > 0 ? '✓ Positive' : '⚠ Negative', 'Should be positive'],
    ],
    columnStyles: { 0: { cellWidth: 45 }, 1: { cellWidth: 30, halign: 'center' }, 2: { cellWidth: 35, halign: 'center' }, 3: { cellWidth: 70 } },
    styles: { fontSize: 9 },
    headStyles: { fillColor: BRAND_COLOR },
  });

  footer(doc);
  doc.save(`${businessInfo.name}_TaxSummary_${businessInfo.taxYear}.pdf`);
}
